"""
Analytical cross-check: closed-form net-section stress on an un-notched L.

Geometry: the full L outline with NO holes and the fillet replaced by a sharp
inside corner (i.e., R -> 0 limiting case). This geometry is not used in the
sweep; it exists solely to produce an independent analytical prediction we can
compare against the FEA pipeline to confirm correctness before we trust it.

Modelling idealization
----------------------
Treat the horizontal flange as a cantilever beam, clamped at the inside corner
(x = W), loaded by a uniformly distributed traction w [MPa] applied downward
on the top face along x in [W, B]. In 2D plane-stress the problem is
per-unit-depth; the cantilever beam properties are then:

    span         L_h = B - W
    load per len q   = w   [N/mm^2 * 1mm_depth = N/mm]
    root moment  M/t = w * L_h^2 / 2                [N*mm / mm_depth]
    section mod  S/t = W^2 / 6                       [mm^2]
    root bending stress   sigma = (M/t) / (S/t) = 3 * w * L_h^2 / W^2

The peak tensile/compressive bending stress occurs at the top (compressive)
and bottom (tensile) fibres of the horizontal flange at the root section.
The corresponding von Mises equals |sigma| (uniaxial state).

This ignores the inside-corner stress singularity (a sharp L has infinite
stress at the re-entrant corner — that's why the real bracket has a fillet).
Compared against FEA on the un-notched L, we therefore sample stress at a
cross-section DISPLACED from the corner, e.g. x = W + probe_offset, to avoid
the singularity region. The predicted value at that section is:

    M(x) / t = w * (B - x)^2 / 2
    sigma_b(x) = 3 * w * (B - x)^2 / W^2
"""

from __future__ import annotations

from dataclasses import dataclass

from .constants import A_VERT_LEN_MM, B_HORIZ_LEN_MM


@dataclass(frozen=True)
class BendingPrediction:
    x: float               # section location (mm from back face)
    sigma_bending: float   # peak fibre bending stress at section [MPa]
    load_w_mpa: float      # distributed load applied [MPa]
    W_mm: float            # flange width [mm]
    L_remaining: float     # (B - x), cantilever tail length at section [mm]


def bending_stress_at_section(x_mm: float,
                              W_mm: float,
                              load_w_mpa: float) -> BendingPrediction:
    """Closed-form peak bending stress at a cross-section of the horizontal
    flange on the un-notched L, treated as a cantilever beam.

    x_mm : location of the section, measured from the back face. Must lie in
           (W_mm, B_HORIZ_LEN_MM).
    """
    if not (W_mm < x_mm < B_HORIZ_LEN_MM):
        raise ValueError(f"x={x_mm} outside cantilever span (W, B)")

    L_rem = B_HORIZ_LEN_MM - x_mm
    sigma = 3.0 * load_w_mpa * L_rem**2 / W_mm**2
    return BendingPrediction(x=x_mm, sigma_bending=sigma,
                             load_w_mpa=load_w_mpa, W_mm=W_mm,
                             L_remaining=L_rem)


def root_bending_stress(W_mm: float, load_w_mpa: float) -> float:
    """Convenience: peak bending stress at the root section x = W (the inside
    corner). This is the theoretical maximum for the un-notched cantilever,
    but note it coincides with the sharp-corner singularity — use it only as
    an upper-bound reference, not for pointwise FEA comparison.
    """
    L_h = B_HORIZ_LEN_MM - W_mm
    return 3.0 * load_w_mpa * L_h**2 / W_mm**2


# ---------------------------------------------------------------------------
# Simplified .geo for the un-notched reference geometry.
# ---------------------------------------------------------------------------
#
# The simplified L has the same outer outline as the full bracket but:
#   - no holes
#   - fillet arc replaced by a right-angle inside corner at (W, W)
#
# Physical-group tags match the full geometry where possible so the solver
# script can run unchanged on either mesh:
#   Surface 1  -> bracket body
#   Curve 10   -> clamped face (back of vertical flange)
#   Curve 20   -> loaded face (top of horizontal flange)
# No "fillet" or "hole" tags on the simplified mesh.

_SIMPLE_GEO_HEADER = """// Auto-generated un-notched L reference geometry.
// Generated by src/fea/analytical.build_simplified_geo().
// Purpose: Day-2 analytical cross-check of the FEA pipeline.
"""


def build_simplified_geo(W_mm: float,
                         h_coarse: float = 3.0,
                         h_fine: float = 0.5,
                         refine_dist: float = 8.0) -> str:
    """Return a Gmsh .geo string for the un-notched L with width W_mm.

    Refinement is applied near the sharp inside corner (which is the hot-spot
    the FEA will over-predict due to the singularity — expected behaviour).
    """
    A = A_VERT_LEN_MM
    B = B_HORIZ_LEN_MM
    W = W_mm

    P = [
        (0.0, 0.0),        # P1
        (B,   0.0),        # P2
        (B,   W),          # P3
        (W,   W),          # P4  <- sharp inside corner (replaces fillet)
        (W,   A),          # P5
        (0.0, A),          # P6
    ]

    lines = [_SIMPLE_GEO_HEADER,
             f"// simplified L: W={W}",
             f"h_coarse = {h_coarse};",
             f"h_fine   = {h_fine};",
             ""]

    for i, (x, y) in enumerate(P, start=1):
        # Put h_fine on the sharp inside corner (P4).
        lc = "h_fine" if i == 4 else "h_coarse"
        lines.append(f"Point({i}) = {{{x:.6f}, {y:.6f}, 0.0, {lc}}};")

    lines += [
        "",
        "Line(101) = {1, 2};",      # bottom
        "Line(102) = {2, 3};",      # free-tip end
        "Line(103) = {3, 4};",      # LOADED top of horizontal flange
        "Line(104) = {4, 5};",      # inside face of vertical flange
        "Line(105) = {5, 6};",      # top of vertical flange
        "Line(106) = {6, 1};",      # CLAMPED back face
        "",
        "Curve Loop(1) = {101, 102, 103, 104, 105, 106};",
        "Plane Surface(1) = {1};",
        "",
        'Physical Surface("bracket", 1) = {1};',
        'Physical Curve("clamped", 10) = {106};',
        'Physical Curve("loaded",  20) = {103};',
        "",
        "// refine near the sharp inside corner (expected to singularity)",
        "Field[1] = Distance;",
        "Field[1].PointsList = {4};",
        "Field[1].Sampling = 100;",
        "Field[2] = Threshold;",
        "Field[2].InField = 1;",
        "Field[2].SizeMin = h_fine;",
        "Field[2].SizeMax = h_coarse;",
        "Field[2].DistMin = 0.0;",
        f"Field[2].DistMax = {refine_dist};",
        "Background Field = 2;",
        "Mesh.MeshSizeExtendFromBoundary = 0;",
        "Mesh.MeshSizeFromPoints = 0;",
        "Mesh.MeshSizeFromCurvature = 0;",
        "Mesh.ElementOrder = 2;",
        "Mesh.Algorithm = 6;",
        "",
    ]
    return "\n".join(lines) + "\n"
